openapi: 3.0.1
info:
  title: Epic Medias API
  description: We have Medias
  version: 1.0.1
servers:
  - url: http://localhost:3001
    variables: {}
    description: Local server
  - url: https://epic-qoiwejqwejiq.herokuapp.com
    variables: {}
    description: Cloud server
tags:
  - name: medias
    description: Operations about medias
paths:
  /medias:
    get:
      tags:
        - medias
      summary: Returns a list of medias.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A list of medias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Media"
        "500":
          $ref: "#/components/responses/GenericServerError"
    post:
      tags:
        - medias
      summary: Create
      description: Adds a new media
      requestBody:
        description: The object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Media"
      responses:
        "201":
          description: The ID of the newly created media
          content:
            application/json:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/GenericServerError"
  /medias/{mediaId}:
    get:
      tags:
        - medias
      summary: Get by Id
      description: Retrieve single Media
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: string
          description: The ID of the Media to retrieve
      responses:
        "200":
          description: The single Media
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Media"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/GenericServerError"
    put:
      tags:
        - medias
      description: Update an existing Media
      summary: Update
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: string
          description: The ID of the Media to update
      requestBody:
        description: Fields to update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Media"
      responses:
        "200":
          description: A list of medias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Media"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/GenericServerError"
    delete:
      tags:
        - medias
      summary: Delete
      description: Delete a specific Media by ID
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: string
          description: The ID of the Media to delete
      responses:
        "204":
          description: Empty Response
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/GenericServerError"
  
  schemas:
    Media:
      type: object
      properties:
        title:
          type: string
        year:
          type: string
        type:
          type: string
    Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string